<?php

declare(strict_types=1);

use yii\db\Migration;

/**
 * Migration for creating the `users` table.
 * Defines user attributes and unique indexes for access token and email.
 */
class m251001_120000_create_users_table extends Migration
{
    /**
     * Creates the `users` table and required indexes.
     */
    public function safeUp(): void
    {
        $this->createTable('users', [
            'id' => $this->bigPrimaryKey()->defaultExpression('GENERATED BY DEFAULT AS IDENTITY'),
            'created_at' => $this->integer(11)->notNull(),
            'updated_at' => $this->integer(11)->notNull(),
            'username' => $this->string(64)->notNull(),
            'password_hash' => $this->string()->notNull(),
            'auth_key' => $this->string(32)->notNull(),
            'access_token' => $this->string(32)->notNull(),
            'email' => $this->string(64)->notNull(),
            'phone' => $this->string(12)->notNull(),
            'status' => $this->tinyInteger(1)->notNull(),
            'agreement_personal_data' => $this->tinyInteger(1)->notNull(),
        ]);

        $this->createIndex('UK__USERS__ACCESS_TOKEN', 'users', 'access_token', true);
        $this->createIndex('UK__USERS__EMAIL', 'users', 'email', true);
    }

    /**
     * Drops the `users` table and its indexes.
     */
    public function safeDown(): void
    {
        $this->dropTable('users');
    }
}
